### PR TITLE
RandomForest model by chigozie

### PR DESCRIPTION
**Pull request by gogzicole**
guys please check out the DecisionTree and RandomForest models i created in the model folder. please drop your comments i would like to know what you think.

i made a model with the dataset as it is, i then made another model using SMOTE to increase he sample size, also the work is encapsulated in an sklearn pipeline so it might be a bit tricky to understand.

### CODE REVIEW

**Comment by mickynnamdi** [comment]
It very obvious the imbalance is worth working on. Noticed randomforest seems to perform more better than any module

**Comment by Echefu-Charles** [comment]
Really impressive work gozie.....your approach can form the bedrock for further investigations and modifications if possible.

**Comment by blennyblex** [comment]
Nice one Gogzicole. The only issue i have with your model is that, Lets look at the classification report of your unsmoted random forest, you got a recall score of 0.95+ for just the pos_label of 0, and 0.6+ for that of "1". Probably you show us the classification metrics of your smoted random forest model, so we can see the precision score of both pos_label. 

Nice approach with pipeline. Cheers

**Comment by gogzicole** [comment]
thank you for pointing that out @blennyblex, i didn't include it because it is not relevant in evaluating the performance of the model, because the recall score and all other metrics are evaluated on the score of the True positive class alone and not of the True negative class.  check the formulas for precision and recall, only TP, FP, and FN are used in evaluation and no instance of TN which stands for the prediction of the negative class 0. So including its score in the report would prove irrelevant and surplus to requirement, because the FN score is a direct measure of the TN class, i.e they are directly proportional, as FN increase TN decreases and vice versa. So if we have a high recall score it simply means that the FN is quite small and hence the TN ( class instance 0) is quite high, because TN + FP = 1(total negative class).

**Comment by aylithe** [comment]
Hi Chigozie, welldone, I noticed you used accuracy as the scoring metric when doing the grid search for both random forest and decision tree models. I'm wondering if we can get a better score by using the f1_score.

**Comment by aylithe** [comment]
Also, I'm wondering why you didn't include the age column among the columns you transformed. Your make_column_transform = [2,4,6,7,8,11], but age is column 0

**Comment by Sillians** [comment]
Hi Gozy, On the section where you carried out the "Feature engineering based on the actual medical values expected from each feature", I think it would be cool to add links to where you got this claim. e.g  Stating that "According to <a href="https://www.ucsfhealth.org/medical-tests/003503">University of California San Francisco medical tests</a>, that the Total CPK normal values ranges from 10 to 120 micrograms per liter (mcg/L)". Let it not look like we are making/using numbers that are not medically accepted.

**Comment by Sillians** [comment]
Hi Gozy, After getting the Dummy variables for the newly engineered features, seems the column names of the encode features changed, for me it doesn't look quite descriptive, i.e "sex_Male", one might think the feature is specifically for the male gender, and probably another column "sex_Female" encoded '1' as Female, same applies to other encoded Features. 
Maybe I am wrong, You can clear me on this please, thanks

**Comment by gogzicole** [comment]
thank you sillians. now normally when you get dummies for a feature containing two classes it creates two new columns for them. For instance the sex column the first column created is for female and the second is for male, in the column for female if the value in the original column of the dataset was female it would write one and write zero for sex male, and vice versa, and same applies for all the rest features, if there are four classes it creates four new columns. Now we drop the first column after the dummies are created to avoid what is called dummy trap. if u check the column that is left u would see it still has the same information as the original, i.e in the sex_male column if the observation is 1 the sex is male and if the observation is 0 the sex is female.

**Pull request merged**
