### PR TITLE
Visualization and EDA

### PR DESCRIPTION
**Pull request by blennyblex**
I uploaded EDA and Model. I did some feature engineering on the dataset , which only took full effect on the Visualization and EDA for better analysis and insights on the data. I didn't apply it fully on the modeling part because it didn't really improve the model. Please check it out and pass your comment.

### CODE REVIEW

**Comment by gogzicole** [comment]
Hmmm!! i simply have no criticism for you EDA work. it has so much insight and explanations, good work especially on the feature engineering part of your work, it was very good.

For the modeling part i'm curious as to why you did not include the engineered data in building the model, it would help the model do a better work at prediction if it is ever deployed. So i encourage you to build another model but this time use the featured data and also don't perform SMOTING lets see how the model would perform. Good work Blessing.

**Comment by blennyblex** [comment]
> Hmmm!! i simply have no criticism for you EDA work. it has so much insight and explanations, good work especially on the feature engineering part of your work, it was very good.
> 
> For the modeling part i'm curious as to why you did not include the engineered data in building the model, it would help the model do a better work at prediction if it is ever deployed. So i encourage you to build another model but this time use the featured data and also don't perform SMOTING lets see how the model would perform. Good work Blessing.

I didnt include it because it didnt improve the model. But for deployment sake, i can include it and upload it again. Thanks for the comment

**Comment by JessicaOjo** [comment]
This is a good work!

**Comment by Gloriaihuoma** [comment]
Your work is self-explanatory, nice work.

**Comment by Sillians** [comment]
> I uploaded EDA and Model. I did some feature engineering on the dataset , which only took full effect on the Visualization and EDA for better analysis and insights on the data. I didn't apply it fully on the modeling part because it didn't really improve the model. Please check it out and pass your comment.

Hi Blessing, I love the detailing in your work, and how you approached the problem. I would suggest you take out the Modeling part since this is just for Exploratory Data Analysis, You can improve on this by doing more extensive EDA, I'm pretty sure more Insights can still be derived from this dataset. Nice Work

**Comment by blennyblex** [comment]
> > I uploaded EDA and Model. I did some feature engineering on the dataset , which only took full effect on the Visualization and EDA for better analysis and insights on the data. I didn't apply it fully on the modeling part because it didn't really improve the model. Please check it out and pass your comment.
> 
> Hi Blessing, I love the detailing in your work, and how you approached the problem. I would suggest you take out the Modeling part since this is just for Exploratory Data Analysis, You can improve on this by doing more extensive EDA, I'm pretty sure more Insights can still be derived from this dataset. Nice Work

I did both EDA and model, not on the same notebook though. The model is under the model folder. The only thing is I have to make my model better. And probably i take out the weighted features i did under the EDA. I will try to do more analysis on the data

**Comment by Sillians** [comment]
> > > I uploaded EDA and Model. I did some feature engineering on the dataset , which only took full effect on the Visualization and EDA for better analysis and insights on the data. I didn't apply it fully on the modeling part because it didn't really improve the model. Please check it out and pass your comment.
> > 
> > 
> > Hi Blessing, I love the detailing in your work, and how you approached the problem. I would suggest you take out the Modeling part since this is just for Exploratory Data Analysis, You can improve on this by doing more extensive EDA, I'm pretty sure more Insights can still be derived from this dataset. Nice Work
> 
> I did both EDA and model, not on the same notebook though. The model is under the model folder. The only thing is I have to make my model better. And probably i take out the weighted features i did under the EDA. I will try to do more analysis on the data

Ohh that's great, Can you explicitly state this if that's what is applicable in your solution approach :
Here 
- Sex - Gender of patient Male = 1, Female =0
- Age - Age of patient
- Diabetes - 0 = No, 1 = Yes
- Anaemia - 0 = No, 1 = Yes
- High_blood_pressure - 0 = No, 1 = Yes
- Smoking - 0 = No, 1 = Yes
- DEATH_EVENT - 0 = No, 1 = Yes

You can check this out https://www.kaggle.com/nayansakhiya/heart-fail-analysis-and-quick-prediction and this https://www.kaggle.com/sanchitakarmakar/heart-failure-prediction-visualization , to see how you can refactor them to come into play in your own approach. 
regards and thanks.

**Review by gauravjain2 — APPROVED** [review]

**Pull request merged**
